### ISSUE TITLE
Arabic language 

### ISSUE THREAD

**Issue by SamoTech** [Kliqqi-CMS/modules#1]
Arabic language become ?????????????????? after import from my blog feed
http://androidsamo.blogspot.com

**Comment by yankidank** [comment]
How are you "importing" the information from your blog? Please provide us with detailed instructions on how to reproduce the issue. 

What module is this issue in regards to?

**Comment by SamoTech** [comment]
when i use rss importer and use my direct feed link it import Arabic as ???????? and try convrt my feed link with rssmix.com it import Arabic as ????? too

this my test site for it http://pligg.hostyd.com/
