### ISSUE TITLE
YANKIDANK: I cannot submit or post a comment on Pligg Support site 

### ISSUE THREAD

**Issue by redwinefireplace** [Kliqqi-CMS/modules#5]
I tried over 10 times at different times. Nothing is posted and when I refresh the page it  gives me that the captcha entered is incorrect, even though It was!

**Comment by chuckroastpligg** [comment]
Yeah I'm having the same issues. I just talked to Yank and we've decided that we're going to actually buy a new server and migrate away from nginx and varnish.

**Comment by redwinefireplace** [comment]
Thank you Chuck! I tried it earlier and I was able to post a comment. :-)
